[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "npm run build"
  publish = "dist"
  function = "./functions"

[context.deploy-preview]
  command = "npm run build:preview"

[[redirects]]
  from = "/brand"
  to = "https://chef-community-components.netlify.app/"
  status = 301

[[redirects]]
  from = "/resources/*"
  to = "https://chef-resource-hub.netlify.app/resources/:splat"
  status = 200