[build]
  command = "hugo"
  publish = "public"
  environment = { HUGO_VERSION = "0.53" }
  
[context.deploy-preview]
command = "hugo -b $DEPLOY_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_URL"