[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "npm run build"
  publish = "dist"
  function = "./functions"

[context.deploy-preview]
  command = "npm run build:preview"

[[redirects]]
  from = "/brand"
  to = "http://marketing-web-communitycomponentlibrary.s3-website-us-west-2.amazonaws.com/"
  status = 301

[[redirects]]
  from = "/resources/*"
  to = "https://deploy-preview-13--relaxed-tesla-8996d3.netlify.app/resources/:splat"
  status = 200