baseurl = "/"
languageCode = "en-us"
title = "Chef Developers: Learn, Connect, Contribute."
assetDir = "../src"
disableKinds = "taxonomyTerm"

[params]
  author = "Chef Web Team: Shaun Yap, Jiajia Li"
  title = "Chef Developer Community"
  description = "once upon a time, there was a great meta description. Unfortunately this isn't it."
  facebook = "https://www.facebook.com/getchefdotcom"
  twitter = "https://twitter.com/chef"
  linkedin = "https://www.linkedin.com/company/chef-software"
  github = "http://chef.github.io/"
  youtube = "https://www.youtube.com/user/getchef"
