baseurl = "/"
languageCode = "en-us"
title = "Chef Developers: Learn, Meet, Connect."
assetDir = "../src"
disableKinds = "taxonomyTerm"

[params]
  author = "Chef Software"
  title = "Chef Community"
  description = "Community is the foundation of Chef."
  facebook = "https://www.facebook.com/getchefdotcom"
  twitter = "https://twitter.com/chef"
  linkedin = "https://www.linkedin.com/company/chef-software"
  github = "https://github.com/chef"
  youtube = "https://www.youtube.com/user/getchef"
  meta_image_sq = "https://chef-marketing-public.s3-us-west-1.amazonaws.com/community-img/meta-community-sq.png"
  meta_image_rect = "https://chef-marketing-public.s3-us-west-1.amazonaws.com/community-img/meta-community-rect.png"

# Sets cache of JSON files to 1h
[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "1h"

[[redirects]]
from = "/products/chef-habitat/"
to = "https://www.habitat.sh/"
status = 301
force = true

[[redirects]]
from = "/products/chef-inspec/"
to = "https://www.inspec.io/"
status = 301
force = true