baseurl = "/"
languageCode = "en-us"
title = "Chef Community"
assetDir = "../src"
disableKinds = "taxonomyTerm"

[params]
  author = "Chef Software"
  title = "Chef Community"
  description = "Community is the foundation of Chef. We believe that the best way to build software is in close collaboration with the people who use it, and the best way to use software is alongside those who build it. Join us, whether online or in person, and let’s build the future of technology together."
  facebook = "https://www.facebook.com/getchefdotcom"
  twitter = "https://twitter.com/chef"
  linkedin = "https://www.linkedin.com/company/chef-software"
  github = "http://chef.github.io/"
  youtube = "https://www.youtube.com/user/getchef"
  meta_image_sq = "/img/Community_Meta_Meta Image_600x300.jpg"
  meta_image_rect = "/img/Community_Meta_Meta Image_800x800.jpg"