baseurl = "/"
languageCode = "en-us"
title = "Chef Developers: Learn, Meet, Connect."
assetDir = "../src"
disableKinds = "taxonomyTerm"

[params]
  author = "Chef Software"
  title = "Chef Community"
  description = "Community is the foundation of Chef."
  facebook = "https://www.facebook.com/getchefdotcom"
  twitter = "https://twitter.com/chef"
  linkedin = "https://www.linkedin.com/company/chef-software"
  github = "http://chef.github.io/"
  youtube = "https://www.youtube.com/user/getchef"


# Disables cache of JSON files
[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "12h"