name: Trigger Netlify Build
on: 
  schedule:
    # Run at 10pm Pacific Time // 5am UTC 
    - cron: '0 5 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps: 
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ef3d1c0bc474b13f53da81d
